### PR TITLE
Travis-CI all the Rubies

### PR DESCRIPTION
**Pull request by benburkert**
Seems to be passing on everything but 1.8.7 of MRI.

https://travis-ci.org/halorgium/rack-client/builds/4699070

### CODE REVIEW

**Comment by halorgium** [comment]
We could ignore 1.8.7 for the moment.

**Comment by benburkert** [comment]
sounds good to me, it seems to be failing due to some weird difference that's only in 1.8.7 of MRI. There is weird call to_proc on the caller stack that doesn't show up for any other rubies. You can test it out by running the specs on the 187-bug branch.

**Comment by benburkert** [comment]
You can see it here: https://travis-ci.org/halorgium/rack-client/builds/4699579

My guess is that a change in rack is triggering this bug: http://stackoverflow.com/questions/4721708/is-this-a-bug-in-methodto-proc-ruby-1-8-7

**Comment by benburkert** [comment]
The EmHttp handler tests have been disabled on MRI 1.8.7 and everything looks good, merging.

**Comment by halorgium** [comment]
:+1:

**Pull request merged**
